### PR TITLE
Fixups for AEIM-685 

### PR DESCRIPTION
**Pull request by malakai97**
See commit messages for details.

### CODE REVIEW

**Comment by aelkiss** [comment]
Regarding changes under `deploy`:

It looks like the only difference between `shared` and `unshared` is:
`append :linked_files, fetch(:shared_local_path)`. This might be nice to factor out but I'm not really sure how we'd accomplish that with Capistrano so I think it's fine to leave the way it is.

That implies:
- "unshared" stuff will get rolled back
- "shared" stuff won't (since it's linked in 

Just to confirm:

- Infrastructure is now just a "shared" thing?
- The intention is that developer config is an "unshared" thing?

One thing that looks not quite right:

- The instances (e.g. deploy/instances/test-norails/instance.yml) appear to have arrays of shared and unshared stuff, but the cap tasks only appear to support deploying a single shared & unshared thing - but it looks like all the shared & unshared things get checked out to a single directory that's then passed to cap?

**Comment by aelkiss** [comment]
I want to make sure this understanding of how infrastructure config now gets uploaded is correct:

- `FileInstanceRepo` constructs an `Instance` from a yaml file that has a list of "shared"`ArchiveReference`s. The infrastructure config should be one of these.

- `Instance#signature` generates a `ReleaseSignature` that points at the infrastructure config (as one of the "shared" `ArchiveReference`s).
- `ReleaseBuilder` takes the `ReleaseSignature`, creates a `shared` and `unshared` path inside a temporary directory, and calls `#add_reference` for each "shared" `ArchiveReference` (which includes the infrastructure config)
-

**Comment by aelkiss** [comment]
- I liked removing knowledge of `git ls-files` from `WorkingDirectory`
- I liked the changes in `Instance` especially with removing the data clump from `ReleaseBuilder.new` and moving its responsibility for building `Signatures` to the `Instance`.

- One question: Should unshared stuff get logged in the LoggedRelease?

**Comment by aelkiss** [comment]
One other thought - calling it `ArchiveReference#latest` is maybe a little confusing. I wonder if `resolve` might be more appropriate? For the case when `commitish` is a commit, the name `latest` doesn't really make sense, but I think `resolve` makes sense for any kind of commitish..

**Comment by aelkiss** [comment]
Looking at the specs..

- spec/support/an_archive_reference.rb seems like an accidental inclusion
- Most of the spec changes seemed to be straightforward changes based on the shared/unshared & archivereference reorganization. I didn't see much that was new that warranted comments - release_builder_spec was the only particular new thing I saw and that looked good to me. It might be worth running coverage just to make sure there isn't anything egregious that got missed, since it's hard to tell at a glance if all the changes are covered with tests..
- Tests fail on Mac OS X because of a hardcoded reference to `/tmp` which is a symlink to `/private/tmp` on Mac OS X - maybe worth fixing if it's super easy at some point

**Comment by aelkiss** [comment]
Looking at coverage.. `Instance#deploy_config` and `ReleaseBuilder#add_reference` aren't really covered, but probably should be...most of the other uncovered stuff is around runners (which is probably fine) and unshared config (which I would expect to be coming soon)

**Comment by malakai97** [comment]
> Assuming all this is correct:

I believe it is all correct.

> Is there a need for the root_dir parameter in production? It looks like right now it's mainly there so we can support testing with this single repository rather than needing to have external dependencies to test. That said I do seem to recall some issue with wanting to do a partial checkout of a repository for samvera app deployment (possibly for a solr config?) and that having to involve an ugly hack with svn somehow, but I don't recall the details or if it's relevant here.

When Noah and I were still having a lot of discussions about ruby deployment, one of the models we settled on for storing things like developer configuration was a single repository with a folder for each project. This supports that, as well as enabling the tests as you say.  I'm not sure if that model is still what we plan to use, but I like the genericity of this feature.

> Is there a reason (apart from supporting the root_dir use case) to check out the shared/unshared git repos to temporary directories rather than checking out directly to the shared/unshared paths we're uploading? 

There's no feature-based reason. It's done this way because the concerns were separate enough from each other; the checkout is performed by git_runner, and the knowledge of the uploaded paths is in our capistrano wrapper.  

>One reason that comes to mind is not wanting to upload .git, but it seems like capistrano could ignore that when uploading or something.

.git is excluded from WorkingDirectory created by GitRunner by way of being excluded from `git ls-files`. 

> Is there a reason (again, apart from supporting the root_dir use case) to check everything out locally and then give it to capistrano to upload rather than just passing the repository URL & commitish to capistrano to pull down? 

I actually began adding this feature this way, but I quickly became uncomfortable with how complex the logic was within capistrano.

> One reason I could think of is that the repositories where this config is located might not be accessible from the target machines - i.e. some of this might be sensitive things that are only committed to a repo local to the deployment server, and we would not necessarily want the deployment user ssh key to have access back to the deployment server to read those repos. Are there other reasons?

The target machines shouldn't have a way of connecting back to the deployhost. Does that obviate this case? I did not understand the case very well.

> One question: Should unshared stuff get logged in the LoggedRelease?

LoggedRelease is probably due for some attention. The original story did not have detailed criteria for what one might want to learn by examining past releases. Unshared stuff should probably be there, yes.

> One other thought - calling it ArchiveReference#latest is maybe a little confusing. I wonder if resolve might be more appropriate? For the case when commitish is a commit, the name latest doesn't really make sense, but I think resolve makes sense for any kind of commitish.

My thinking was that if you ask for the latest commit in a branch, it makes sense to get the ref to that branch's head. But if you ask for the latest commit _of a commit_, well then you'd expect to get just that.  The trouble with `#resolve` is it sounds like it does the same thing as `#at`.  Perhaps just elaborating on its documentation would be sufficient?

> spec/support/an_archive_reference.rb seems like an accidental inclusion
Indeed.

> Some tests fail on Mac OS X because of a hardcoded reference to /tmp which is a symlink to /private/tmp on Mac OS X - maybe worth fixing if it's super easy at some point

It's worth fixing, but someone with a Mac will have to do it since I can't reproduce the issue. :D

**Comment by aelkiss** [comment]
What about:

```ruby
    def resolve(new_commitish=commitish)
      self.class.at(url, new_commitish, root_dir)
    end
```
(instead of `ArchiveReference#latest` vs `ArchiveReference#at`)

**Comment by aelkiss** [comment]
Here is a fix for the test failures on Mac OS X - I figure this should probably be on a separate PR, but let's get this merged first.

```diff
diff --git a/spec/filesystem_spec.rb b/spec/filesystem_spec.rb
index a6dd532..3d36b56 100644
--- a/spec/filesystem_spec.rb
+++ b/spec/filesystem_spec.rb
@@ -38,7 +38,7 @@ module Fauxpaas
       describe "#chdir" do
         it "changes directory" do
           fs.chdir("/tmp") do
-            expect(`pwd`.strip).to eql("/tmp")
+            expect(`pwd`.strip).to eql(File.realpath("/tmp"))
           end
         end

@@ -68,7 +68,7 @@ module Fauxpaas
           end
           it "yields the temporary dir" do
             fs.mktmpdir do |dir|
-              expect(dir.parent).to eql(Pathname.new("/tmp"))
+              expect(dir.parent).to eql(Pathname.new(ENV["TMPDIR"].sub(/\/$/,'') || "/tmp"))
             end
           end
           it "deletes it when the block completes" do
```

**Comment by aelkiss** [comment]
I'm happy with your comments above regarding the choices to:
  - check things out locally (rather than using cap)
  - support checking out a subdirectory (and thus in part, the decision to check out to a tmp dir and then copy to the upload dir)

I think it's still waiting on a couple small fixes before we merge:

- remove `spec/support/an_archive_reference.rb`
- I'd like your thoughts on the proposed merger of `ArchiveReference#at` and `ArchiveReference#latest` to `ArchiveReference#resolve` above?

**Comment by malakai97** [comment]
* Added spec for ReleaseBuilder coverage
* Added spec for Instance#deploy_config coverage
* Improved ArchiveReference `#latest` documentation. The name `resolve` is just much less clear to me.
* Add unshared to LoggedRelease
* Change LoggedRelease#to_s to output a multiline string (gasp)

**Pull request merged**
