### PR TITLE
Feature/deploy releases

### PR DESCRIPTION
**Pull request by malakai97**
In the broadest strokes, this pr:
* Removes some reliance on capistrano by pushing the functionality into the application.
* Reimagines instance as primarily holding the references to the related (git) archives
* Reimagines release into Release and Logged Release

### CODE REVIEW

**Comment by aelkiss** [comment]
IDK why Travis is failing, works for me...

**Comment by aelkiss** [comment]
In cdfb7ff: The config is duplicated between fauxpaas.rb and components.rb - should have been removed from fauxpaas.rb?

**Comment by aelkiss** [comment]
In 1ca0b2e - https://github.com/mlibrary/fauxpaas/pull/14/files#diff-f54aea5fd300c0c294907b3216416b4eR20  is just duplicating the code from https://github.com/mlibrary/fauxpaas/pull/14/files#diff-0772e8d7064112d07e69a67b39ac09c7R9 - I'd rather see the code test a concrete example. If you wanted, you could mock `GitReference` and `ReleaseSignature` but that might be overkill given the limited behavior of those two things right now.

**Comment by aelkiss** [comment]
https://github.com/mlibrary/fauxpaas/pull/14/commits/da18e34f8036548d31d62ba22d7104e3c5a5f7ad#diff-41c7e1d854088ca87783adc00af47022R17 - the `ls_remote(...)&.first&.first` is not very intention-revealing here. This is the only place `GitRunner#ls_remote` is being used - would it make sense to change that to a more intention-revealing name and have it deal with the `&.first&.first` part?

**Comment by aelkiss** [comment]
https://github.com/mlibrary/fauxpaas/commit/da18e34f8036548d31d62ba22d7104e3c5a5f7ad#diff-a20cd1daef7b3791771c4351614a6f53R12 - The `SpoofedGitRunner` is complicated enough that it's a little bit confusing here to unpack how much this is testing the `SpoofedGitRunner` vs. the `LocalArchive`. Not sure I have any real suggestion to make here, though.

**Comment by aelkiss** [comment]
Well, a couple thoughts about how to improve those tests:
* it might make the tests more readable and intention-revealing just to put the literals you expect in the test rather than getting them from the `SpoofedGitRunner`. That might also allow you to simplify `SpoofedGitRunner`.
* I think the reason I'm having trouble telling how much these test the `Archive` vs. the `SpoofedGitRunner` is that it isn't immediately obvious how the test cases correspond to branches in the `LocalArchive`/`RemoteArchive` vs. the data in the `SpoofedGitRunner`. This could be a case where a comment in the `Archive`s for each case could help, or just extracting each case like e.g. `git_runner.rev_parse("#{commitish}^{}")` to a more intention-revealing method name if you really don't want to use a comment (see also the comment about `&.first&.first` above)

**Comment by aelkiss** [comment]
https://github.com/mlibrary/fauxpaas/commit/da18e34f8036548d31d62ba22d7104e3c5a5f7ad#diff-dbaf7a3379acda8b30d55d78e3b8c995R35
https://github.com/mlibrary/fauxpaas/commit/da18e34f8036548d31d62ba22d7104e3c5a5f7ad#diff-a20cd1daef7b3791771c4351614a6f53R35

seems like a good case for shared examples here?

**Comment by aelkiss** [comment]
Unrelated thought: We're using this dependency-injectable `Filesystem` pattern enough that it might make sense to extract this to a separate gem...?

**Comment by aelkiss** [comment]
(D) It doesn't look like you're using this any more... https://github.com/mlibrary/fauxpaas/pull/14/commits/914d21483cacd13cdad1f93b4cab8881acb0b615#diff-662d690351be28d7064a8289f45a251eR8

**Comment by aelkiss** [comment]
(E) https://github.com/mlibrary/fauxpaas/pull/14/files#diff-953627032c9161082e82670db30cc86eR23 -
 Something feels odd here - we're asking the `Instance` to generate some things and do some things that we then need to keep track of, understand a bit, and pass back to the `Instance`. It also won't work as is since `status` isn't defined.. I think my inclination would be to put this kind of orchestration inside the `Instance` and be able to say for example:

```ruby
       instance = Fauxpaas.instance_repo.find(instance_name)
       # you could still check the result and display success/failure here
       instance.deploy(reference)
       # this should be harmless/no-op even if the deployment failed
       Fauxpaas.instance_repo.save(instance)
```

and then in `Instance`:

```ruby
class Instance
  # returns the status of the deployment
  def deploy(reference)
    signature = signature(reference)
    release(signature).deploy.tap do |status|
      log_release(LoggedRelease.new(signature)) if status.success?
    end
  end
end
```

I might also prefer having `Release#signature` public to avoid the temporary:

```ruby
class Instance
  # returns the status of the deployment
  def deploy(reference)
    release(signature(reference)).deploy.tap do |status|
      log_release(release) if status.success?
    end
  end

  def log_release(release)
      releases << LoggedRelease.new(release.signature)
  end
end
```

**Comment by aelkiss** [comment]
(F): https://github.com/mlibrary/fauxpaas/pull/14/commits/4142e8adbc41f9dcf7a12143511b03bf380d6435#diff-e33a1cddebb5f1bf559f8b2fc16b09f5R55 - Agreed - and in fact now we've split up knowledge about Capistrano between `CapRunner`, `Instance`, and `Deployment`. We could put that in `CapRunner`, but I think we're conceiving of `CapRunner`'s responsibility as just marshalling the arguments to Capistrano and actually running it. Would it make sense to keep the `CapistranoDeployer` abstraction and have the `DeployConfig` provide that rather than the `CapRunner` directly?

**Comment by aelkiss** [comment]
(F.2): https://github.com/mlibrary/fauxpaas/pull/14/files#diff-e33a1cddebb5f1bf559f8b2fc16b09f5R48 
We could avoid some deeply-chained dependencies -
 `deploy_archive.deploy_config(...).runner.run(...)`) here and `deploy_config(...).runner.run(...)` in `Release`

We should also make deploy_archive.latest the default for DeployArchive#deploy_config.

Let's say we keep the `CapistranoDeployer` as above; we might end up with something like:

```ruby
class DeployArchive
  def deploy_config(reference=latest)
    ...
  end
end

class Instance
  def deployer
    @deployer ||= CapistranoDeployer.new(deploy_archive.deploy_config)
  end

  def deploy
    release(signature(reference)).deploy_with(deployer).tap do |status|
      log_release(release) if status.success?
    end
  end
end

class Release
  def deploy_with(deployer)
    ...
    deployer.deploy(deploy_config.appname,deploy_options(infrastructure_path))
    ...
  end
end
```

**Comment by aelkiss** [comment]
(G) - Why are we serializing/deserializing `Infrastructure`? It looks like the only reason to have it deserialized is to determine if two `Release`s are equal, which is in turn only used to compare if two `Instance`s are equal, and all that equality-checking stuff ultimately only seems to be used in the tests, not in anything called by the CLI... Not sure where that leaves us, but maybe consider if we could put more of the equality-checking machinery in the tests, or just test less of this and wait until it's required by any of the use cases?

**Comment by malakai97** [comment]
* A. Removed in 43c5b80
* B. Example concretified. See ca8e2e0
* C1-4. After reviewing these comments, I've pushed down the local vs. remote git
  responsibility to the GitRunner, which now has subclasses LocalGitRunner and
  RemoteGitRunner. This removed the need for this separation in Archive.

  These changes allowed the simplification of SpoofedGitRunner, which has also
  had its method names changed to hopefully be more clear.

  See 0c5025f

* D. Removed in 408934d
* E. Hmm. It is weird. `#signature` and `#release` are separated in this way because
  it's vital that we can reconstitute Releases from  ReleaseSignatures and then
  deploy them.  On the other hand, logging the release as a separate step feels very
  far off. Resolving (F) might clear this up.
* F. Regarding the capistrano responsibility, I am still digesting your comments
  and thinking about the problem.

  > We should also make deploy\_archive.latest the default for DeployArchive#deploy\_config.

  This knowledge of the usual case seems like it originates outside of
  DeployArchive, so I am reticent to put the default there.

* G. Indeed. Some of this serialization was added, then the need for it was removed.
  The `#eql?` support is also there entirely for the tests, which really bugs me.
  At the same time, query methods that just return values are preferable, but we
  end up needing the equality methods to check them.

**Comment by aelkiss** [comment]
0c502: Yes, I think this is much easier to digest now. However, you will want to test the behavior for both the local and remote cases when the reference can't be resolved -- I saw you added a `UnknownReferenceError` but it doesn't appear to be used. Right now, if the `commitish` can't be resolved, `LocalGitRunner` will just return the `commitish` but `RemoteGitRunner` will throw a `NoMethodError: undefined method `split' for nil:NilClass`.

**Comment by aelkiss** [comment]
E/F: with respect to`DeployArchive/DeployConfig`: I see what you're saying here - In particular I think the point about reconstituting `Release`s from `ReleaseSignature`s is why the knowledge of the default should be in `Instance`... However:

- I would contend that it is not actually vital that we be able to do that - at least not now as our requirements stand - nothing in `Fauxpaas::CLI::Main` build a `Release` given anything but the source reference, and AFAICT none of the stories in https://tools.lib.umich.edu/jira/browse/AEID-74?jql=text%20~%20%22ruby%20deployment%22 require that. If there is a requirement to do this (i.e. re-execute a previous release), we should add a story for it.

- Putting the knowledge in `Instance` doesn't preclude supplying a signature to deploy rather than a reference. For example what if we had something like:

```ruby
class Instance
  def deploy(reference: nil, signature: signature(reference))
    release(signature).deploy
  end
end
```

And as far as logging.. what if we had the `Release` yield a `LoggedRelease` on success? Alternatively we could have the `Release` know about the `Instance` in order to log it, but introducing that additional dependency seems unwise. We might want to rename `LoggedRelease` to `ReleaseInfo` or something to make this a little more clear (i.e. it seems odd that you have to log a `LoggedRelease` - wouldn't a `LoggedRelease` already be logged?)

```ruby
class Instance
  def deploy(reference: nil, signature: signature(reference))
    release(signature).deploy do |release_info|
       log_release(release_info)
    end
  end
end

class Release
  def deploy
     ...
     _, _, status = ...
     yield ReleaseInfo.new(signature) if status.success?
     status
  end
end
```




```

```

**Comment by malakai97** [comment]
* F.
  * Archive#latest is now the default for Archive#reference
  * Added the class Cap, which further wraps capistrano.
  * Added Instance#interrogator, which returns an object that has a view into the current
  state of the instance.
  * I believe the capistrano knowledge is now well-isolated. I'm happy with how it turned out.
* E. After trying several permutations of this, including one based off your suggestions,
  I could not find anything that eliminated the procedural code without also introducing
  other complexities. I decided to keep this as-is, because what's there now should
  at least be didactic enough to be fixed later as additional needs put pressure on the
  design.

**Comment by aelkiss** [comment]
I think this looks good.. a couple (hopefully small) comments:

- I'm not sure the Infrastructure knowledge belongs in Cap#deploy. I was
  thinking in `Release`:

```ruby
def deploy
  fs.mktmpdir do |dir|
    infrastructure_path = Pathname.new(dir) + "infrastructure.yml"
    fs.write(infrastructure_path, YAML.dump(infrastructure.to_hash))

    deploy_config
      .runner
      .deploy(infrastructure, deploy_options(infrastructure_path))
  end
end
```

(and keeping `Release#deploy_options` as it was before)

- `DeployConfig#runner` is now confusingly-named since it returns a `Cap`, not
  a `CapRunner`. I think the purpose of `Cap` is to translate between our
domain actions and the Capistrano tasks, we might call it a `CapAdapter` or
something, and then call it `DeployConfig#adapter`? That might be too abstract,
but I'm not sure what else to call it without using the 'deployer' name. Is
there something that captures Capistrano's domain of "deployment and related
things around deployment"...?

**Comment by aelkiss** [comment]
I noticed a bug in `Instance#eql?`: `Instance` checks that `releases == other.releases`, but `releases` is actually expected to be an array of `LoggedRelease`s, and `LoggedRelease` doesn't override `eql?`. (`Release` does, though). I think you were going to change the name to `Instance#release_history`? The tests only pass because the place in which you're doing equality-checking for instances, the instance just has a `double(:release)`, not a real one..

**Pull request merged**
